GH-186: Introduce DDS Sessions.

diff --git a/bin/dds-server b/bin/dds-server
--- a/bin/dds-server
+++ b/bin/dds-server
@@ -3,10 +3,10 @@
 #
 #
 # Usage:
-#      dds-server start|restart|stop|status|getbins
+#      dds-server start|restart <session ID>|stop <session ID> |status <session ID>|getbins
 #
 # Supported OS:
-#    Linux, Mac OS X (tested on 10.9)
+#    Linux, Mac OS X (min 10.9)
 #
 #
 # Notes:
@@ -14,6 +14,8 @@
 #    Users could provide own version of the pre-compiled bins and avoid of downloading of them.
 #
 #
+
+USAGE="Usage: $(basename "$0") {start [-s]|restart <session ID> [-s]|stop <session ID>|status <session ID>|getbins <session ID>}"
 
 SERVER_OS=$(uname -s 2>&1)
 
@@ -37,8 +39,38 @@ if [ -z "$DDS_CFG" ]; then
   echo "You can create the default config file by using: dds-user-defaults -f -d -c ~/.DDS/DDS.cfg"
   exit 1
 fi
+
+###### Prep DDS Session
+if [ "$1" == "start" ]; then
+	DDS_SESSION_ID=$(dds-commander prep-session)
+	if [ -n "$DDS_SESSION_ID" ]; then
+  	  echo "DDS session ID: $DDS_SESSION_ID"
+	else
+  	  echo "Failed to create DDS session"
+  	  return 1
+	fi
+elif [ -z "$1" ]; then
+	echo "$USAGE"
+	exit 1
+fi
+
+if [ "$1" != "start" ]; then
+	DDS_SESSION_ID=$2
+	# try using the default session ID if no ID is provided
+	if [ -z $DDS_SESSION_ID ]; then
+		DDS_SESSION_ID=$(dds-user-defaults  --default-session-id)
+	fi
+	echo "Using DDS Session ID: $DDS_SESSION_ID"
+	# Standard Session ID is 36 chars
+	sessionid_len=${#DDS_SESSION_ID}
+	if [ $sessionid_len != 36 ]; then
+  		echo "Bad Session ID"
+  		exit 1
+	fi
+fi
+
 #######
-WORK_DIR=$(dds-user-defaults -V --key server.work_dir)
+WORK_DIR=$(dds-user-defaults --session $DDS_SESSION_ID -V --key server.work_dir)
 if (( $? != 0 )) ; then
   echo "ERROR: Your DDS user defaults can't be used with this version of DDS."
   echo "If you want to continue to use this version of DDS, you have the following options:"
@@ -59,7 +91,7 @@ DDS_URL=" http://dds.gsi.de/releases/add"
 # ************************************************************************
 server_status()
 {
-  commander_pid=$(dds-info  --commander-pid  2>/dev/null)
+  commander_pid=$(dds-info  --session $DDS_SESSION_ID --commander-pid  2>/dev/null)
   if [ -n "$commander_pid" ]; then
     echo "DDS commander server: $commander_pid"
     return 0
@@ -229,7 +261,7 @@ create_dir_hierarchy()
   #   create_dir "$WORK_DIR/etc"
   #   create_dir "$DDS_SRV_LOGDIR"
   #   # create workers' sandbox
-  local dir=$(eval dirname $(dds-user-defaults --wrkscript))
+  local dir=$(eval dirname $(dds-user-defaults --session $DDS_SESSION_ID --wrkscript))
   create_dir "$dir"
   return 0
 }
@@ -240,8 +272,8 @@ _start()
 {
   # S T A R T I N G the server
   echo "Starting DDS commander..."
-  eval LOG_DIR=$(dds-user-defaults -V --key server.log_dir)
-  $DDS_LOCATION/bin/dds-daemonize "$LOG_DIR" dds-commander start
+  eval LOG_DIR=$(dds-user-defaults --session $DDS_SESSION_ID -V --key server.log_dir)
+  $DDS_LOCATION/bin/dds-daemonize "$LOG_DIR" dds-commander --session $DDS_SESSION_ID start
   if (( $? != 0 )); then
     echo "Error: can't start dds-commander."
     return 1
@@ -254,6 +286,10 @@ _start()
   echo "------------------------"
   status
   echo "------------------------"
+  
+  # Set default Session ID
+  local default_sid_file=$(dds-user-defaults --default-session-id-file 2>/dev/null)
+  echo  $DDS_SESSION_ID > $default_sid_file
 
   return 0
 }
@@ -262,7 +298,7 @@ _start()
 # ************************************************************************
 start()
 {
-  local commander_pid=$(dds-info --commander-pid 2>/dev/null)
+  local commander_pid=$(dds-info --session $DDS_SESSION_ID --commander-pid 2>/dev/null)
   # don't need to do anything
   if [ -n "$commander_pid" ]; then
     echo "DDS Commander is running already."
@@ -310,12 +346,12 @@ wait_and_kill()
 # ************************************************************************
 stop()
 {
-  $DDS_LOCATION/bin/dds-commander stop
+  $DDS_LOCATION/bin/dds-commander --session $DDS_SESSION_ID stop
 
-  local commander_pid=$(dds-info --commander-pid 2>/dev/null)
+  local commander_pid=$(dds-info --session $DDS_SESSION_ID --commander-pid 2>/dev/null)
 
   if [ -z "$commander_pid" ]; then
-    return 0
+	  return 0
   fi
 
   echo "Stopping DDS server..."
@@ -360,9 +396,10 @@ fi
 
 
 check_only_local_wn_bins="false"
-if [ "$2" = "-s" ]; then
+if [ "$2" == "-s" ] || [ "$3" == "-s" ]; then
   check_only_local_wn_bins="true"
 fi
+
 
 # star|stop|status|getbins
 case "$1" in
@@ -393,7 +430,7 @@ case "$1" in
   RETVAL=$?
   ;;
   *)
-  echo "Usage: $(basename "$0") {start [-s]|restart [-s]|stop|status|getbins}"
+  echo "$USAGE"
   exit 1
 esac
 
