run_test.sh: add option which allows to run multiple iterations

diff --git a/run_test.sh.in b/run_test.sh.in
--- a/run_test.sh.in
+++ b/run_test.sh.in
@@ -1,95 +1,116 @@
 #! /usr/bin/env bash
 
+# Defaults
+install_dir="@CMAKE_INSTALL_PREFIX@"
+num_iterations="1"
+
+# Parse command line options
+while getopts d:n: flag
+do
+    case "${flag}" in
+        d) install_dir=${OPTARG};;
+        n) num_iterations=${OPTARG};;
+    esac
+done
+
+if ! [[ "${num_iterations}" =~ ^[0-9]+$ ]]
+then
+   echo "-n option must be a positive integer"
+   exit 1
+fi
+
+echo "Start test with the following arguments:"
+echo "   install dir: '${install_dir}'"
+echo "   number of iterations: ${num_iterations}"
 
 clean_up()
 {
- popd
- exit 1
+  popd
+  exit 1
 }
 
 trap clean_up SIGHUP SIGINT SIGTERM
 
-
-exec_test() {
-
-if [ -e "./$1" ]; then
-	echo ">>> Processing $1"
-	"./$1" $2 || clean_up
-	echo
-else
-	echo "WARNING: can't find $1"
-fi
-
+exec_test() 
+{
+   if [ -e "./$1" ]; then
+      echo ">>> Processing $1"
+     "./$1" $2 || clean_up
+     echo
+   else
+     echo "WARNING: can't find $1"
+   fi
 }
-
-if [ -z "$1" ]
-then
-   install_dir="@CMAKE_INSTALL_PREFIX@"
-else
-   install_dir="$1"
-fi
 
 source "${install_dir}/DDS_env.sh"
 
 pushd $(pwd)
 cd "${install_dir}/tests"
 
-
 echo "Working directory: $(pwd)"
 echo
 
-echo "----------------------"
-echo "MiscCommon UNIT-TESTs"
-echo "----------------------"
-exec_test "MiscCommon_test_MiscUtils"
-#  we use --catch_system_errors=no here to prevent BOOST catching SIGCHLD
-#exec_test "MiscCommon_test_Process" "--catch_system_errors=no"
-exec_test "MiscCommon_test_SysHelper"
-#exec_test "MiscCommon_test_FindCfgFile"
-exec_test "MiscCommon_test_Logger"
-exec_test "MiscCommon_test_wordexp"
+exec_all()
+{
+   echo "----------------------"
+   echo "MiscCommon UNIT-TESTs"
+   echo "----------------------"
+   exec_test "MiscCommon_test_MiscUtils"
+   #  we use --catch_system_errors=no here to prevent BOOST catching SIGCHLD
+   #exec_test "MiscCommon_test_Process" "--catch_system_errors=no"
+   exec_test "MiscCommon_test_SysHelper"
+   #exec_test "MiscCommon_test_FindCfgFile"
+   exec_test "MiscCommon_test_Logger"
+   exec_test "MiscCommon_test_wordexp"
 
-echo "----------------------"
-echo "dds-topology UNIT-TESTs"
-echo "----------------------"
-exec_test "dds_topology_lib-tests" "--catch_system_errors=no"
+   echo "----------------------"
+   echo "dds-topology UNIT-TESTs"
+   echo "----------------------"
+   exec_test "dds_topology_lib-tests" "--catch_system_errors=no"
 
-echo "----------------------"
-echo "dds-topology performance UNIT-TESTs"
-echo "----------------------"
-exec_test "dds_topology_lib-performance-tests" "--catch_system_errors=no"
+   echo "----------------------"
+   echo "dds-topology performance UNIT-TESTs"
+   echo "----------------------"
+   exec_test "dds_topology_lib-performance-tests" "--catch_system_errors=no"
 
-echo "----------------------"
-echo "Protocol UNIT-TESTs"
-echo "----------------------"
-exec_test "dds_protocol_lib-ProtocolMessage-tests"
-#exec_test "dds-protocol-lib-client-tests"
-#exec_test "dds-protocol-lib-server-tests"
+   echo "----------------------"
+   echo "Protocol UNIT-TESTs"
+   echo "----------------------"
+   exec_test "dds_protocol_lib-ProtocolMessage-tests"
+   #exec_test "dds-protocol-lib-client-tests"
+    #exec_test "dds-protocol-lib-server-tests"
 
-echo "----------------------"
-echo "Commander UNIT-TESTs"
-echo "----------------------"
-exec_test "dds-scheduler-tests" "--catch_system_errors=no"
+   echo "----------------------"
+   echo "Commander UNIT-TESTs"
+   echo "----------------------"
+   exec_test "dds-scheduler-tests" "--catch_system_errors=no"
 
-echo "----------------------"
-echo "Intercom lib UNIT-TESTs"
-echo "----------------------"
-exec_test "dds_intercom_lib-tests" "--catch_system_errors=no"
+   echo "----------------------"
+   echo "Intercom lib UNIT-TESTs"
+   echo "----------------------"
+   exec_test "dds_intercom_lib-tests" "--catch_system_errors=no"
 
-echo "----------------------"
-echo "dds-user-defaults UNIT-TESTs"
-echo "----------------------"
-exec_test "dds-user-defaults-tests"
+   echo "----------------------"
+   echo "dds-user-defaults UNIT-TESTs"
+   echo "----------------------"
+   exec_test "dds-user-defaults-tests"
 
-echo "----------------------"
-echo "dds_tools_lib-protocol-tests UNIT-TESTs"
-echo "----------------------"
-exec_test "dds_tools_lib-protocol-tests"
+   echo "----------------------"
+   echo "dds_tools_lib-protocol-tests UNIT-TESTs"
+   echo "----------------------"
+   exec_test "dds_tools_lib-protocol-tests"
 
-echo "----------------------"
-echo "dds_tools_lib-session-tests UNIT-TESTs"
-echo "----------------------"
-exec_test "dds_tools_lib-session-tests"
+   echo "----------------------"
+   echo "dds_tools_lib-session-tests UNIT-TESTs"
+   echo "----------------------"
+   exec_test "dds_tools_lib-session-tests"
+}
+
+for i in `seq 1 ${num_iterations}`;
+do
+   echo "Start iteration $i"
+   exec_all
+done
 
 popd
 
